### ISSUE TITLE
Building Fails for macOS Ventura arm64 

### ISSUE THREAD

**Issue by bcortens** [viaduck/icu-cmake#7]
Hello,
Having solved the android cross compile I am now unable to compile it for macOS I suspect it is trying to use arguments for the gcc compiler when it should be using clang arguments. Created a clean project in CLion for macOS Ventura and then just added the subrepo to my project and set the following in my CMakeLists:

Note: SYSTEM_ICU ON doesn't work either.

Right now I have a secondary CMakeLists file for when building for macOS that uses the standard find_package rather than this project (which I would prefer since it decouples my code from the system code). The standard find_package did work but I had to  manually change the icu include dirs in the CLion CMake cache variables in the project settings - setting them in various CMakeLists files didn't seem to work for some reason in CLion.

```
set(SYSTEM_ICU OFF CACHE BOOL "" FORCE)
set(BUILD_ICU ON CACHE BOOL "" FORCE)
set(ICU_BUILD_VERSION "72.1" CACHE STRING "" FORCE)
set(ICU_STATIC OFF CACHE BOOL "" FORCE)

add_subdirectory(libs/icu-cmake)

add_executable(cpp-icu main.cpp)

target_link_libraries(
        cpp-icu
        icu)
```
[config.log](https://github.com/viaduck/icu-cmake/files/11200946/config.log)

**Comment by roussosalex** [comment]
First, your issue seems to be related to the default compiler LLVM but being recognized as GCC by CMake.

**Comment by roussosalex** [comment]
Your issue seems to be related to the [default compiler LLVM being recognized as GCC by configure](https://stackoverflow.com/a/20926441). You could try installing `gcc` and either setting it as your default compiler (`/usr/bin/cc`) or using it directly by setting `-DICU_CFG_OPTIONS="CC=gcc-10"`, replacing it by your version of gcc. 

If that does not work, please check that the paths used by configure exist and point to the correct executables and please post the result of `gcc -v` on your installed gcc version. 

> Note: SYSTEM_ICU ON doesn't work either.

In any case, `SYSTEM_ICU=ON` should have worked as it just [redirects to the standard `find_package` ](https://github.com/viaduck/icu-cmake/blob/master/CMakeLists.txt#L49)anyways. Could you post your log or the error message?
